version: "3.9"

services:
  postgres:
    container_name: postgres-auth
    image: postgres:${PG_VERSION}-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    container_name: redis-auth
    image: redis:${REDIS_VERSION}-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./redis:/data

  nginx:
    container_name: nginx-auth
    image: nginx:${NGINX_VERSION}-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/auth.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-api
    ports:
      - "80:80"

  auth-api:
    container_name: flask-auth-api
    restart: always
    build:
      context: ./application
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-auth
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"